"""add title to sessions

Revision ID: 2e388de58156
Revises: e659e8c84391
Create Date: 2026-08-31 23:08:47.865955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e388de58156'
down_revision: Union[str, Sequence[str], None] = 'e659e8c84391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'title')
    op.add_column(
    'sessions',
    sa.Column(
        'title',
        sa.Text(),
        nullable=False,
        server_default='New Chat'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'title')
    op.add_column(
    'sessions',
    sa.Column(
        'title',
        sa.Text(),
        nullable=False,
        server_default='New Chat'
    )
)
    # ### end Alembic commands ###
