"""add title to sessions

Revision ID: e659e8c84391
Revises: 2f0cacda1eb1
Create Date: 2026-08-31 22:54:46.368032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e659e8c84391'
down_revision: Union[str, Sequence[str], None] = '2f0cacda1eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'title')
    # ### end Alembic commands ###
